const List<Map<String, String>> countryCodes = [
  {'code': '+54', 'flag': '🇦🇷', 'name': 'Argentina'},
  {'code': '+93', 'flag': '🇦🇫', 'name': 'Afganistán'},
  {'code': '+355', 'flag': '🇦🇱', 'name': 'Albania'},
  {'code': '+49', 'flag': '🇩🇪', 'name': 'Alemania'},
  {'code': '+376', 'flag': '🇦🇩', 'name': 'Andorra'},
  {'code': '+244', 'flag': '🇦🇴', 'name': 'Angola'},
  {'code': '+1268', 'flag': '🇦🇬', 'name': 'Antigua y Barbuda'},
  {'code': '+966', 'flag': '🇸🇦', 'name': 'Arabia Saudita'},
  {'code': '+213', 'flag': '🇩🇿', 'name': 'Argelia'},
  {'code': '+374', 'flag': '🇦🇲', 'name': 'Armenia'},
  {'code': '+61', 'flag': '🇦🇺', 'name': 'Australia'},
  {'code': '+43', 'flag': '🇦🇹', 'name': 'Austria'},
  {'code': '+994', 'flag': '🇦🇿', 'name': 'Azerbaiyán'},
  {'code': '+1242', 'flag': '🇧🇸', 'name': 'Bahamas'},
  {'code': '+973', 'flag': '🇧🇭', 'name': 'Baréin'},
  {'code': '+880', 'flag': '🇧🇩', 'name': 'Bangladés'},
  {'code': '+1246', 'flag': '🇧🇧', 'name': 'Barbados'},
  {'code': '+32', 'flag': '🇧🇪', 'name': 'Bélgica'},
  {'code': '+501', 'flag': '🇧🇿', 'name': 'Belice'},
  {'code': '+229', 'flag': '🇧🇯', 'name': 'Benín'},
  {'code': '+375', 'flag': '🇧🇾', 'name': 'Bielorrusia'},
  {'code': '+591', 'flag': '🇧🇴', 'name': 'Bolivia'},
  {'code': '+387', 'flag': '🇧🇦', 'name': 'Bosnia y Herzegovina'},
  {'code': '+267', 'flag': '🇧🇼', 'name': 'Botsuana'},
  {'code': '+55', 'flag': '🇧🇷', 'name': 'Brasil'},
  {'code': '+673', 'flag': '🇧🇳', 'name': 'Brunéi'},
  {'code': '+359', 'flag': '🇧🇬', 'name': 'Bulgaria'},
  {'code': '+226', 'flag': '🇧🇫', 'name': 'Burkina Faso'},
  {'code': '+257', 'flag': '🇧🇮', 'name': 'Burundi'},
  {'code': '+975', 'flag': '🇧🇹', 'name': 'Bután'},
  {'code': '+238', 'flag': '🇨🇻', 'name': 'Cabo Verde'},
  {'code': '+855', 'flag': '🇰🇭', 'name': 'Camboya'},
  {'code': '+237', 'flag': '🇨🇲', 'name': 'Camerún'},
  {'code': '+1', 'flag': '🇨🇦', 'name': 'Canadá'},
  {'code': '+236', 'flag': '🇨🇫', 'name': 'Chad'},
  {'code': '+56', 'flag': '🇨🇱', 'name': 'Chile'},
  {'code': '+86', 'flag': '🇨🇳', 'name': 'China'},
  {'code': '+357', 'flag': '🇨🇾', 'name': 'Chipre'},
  {'code': '+57', 'flag': '🇨🇴', 'name': 'Colombia'},
  {'code': '+269', 'flag': '🇰🇲', 'name': 'Comoras'},
  {'code': '+242', 'flag': '🇨🇬', 'name': 'Congo'},
  {'code': '+243', 'flag': '🇨🇩', 'name': 'Congo (RDC)'},
  {'code': '+82', 'flag': '🇰🇷', 'name': 'Corea del Sur'},
  {'code': '+850', 'flag': '🇰🇵', 'name': 'Corea del Norte'},
  {'code': '+506', 'flag': '🇨🇷', 'name': 'Costa Rica'},
  {'code': '+225', 'flag': '🇨🇮', 'name': 'Costa de Marfil'},
  {'code': '+385', 'flag': '🇭🇷', 'name': 'Croacia'},
  {'code': '+53', 'flag': '🇨🇺', 'name': 'Cuba'},
  {'code': '+45', 'flag': '🇩🇰', 'name': 'Dinamarca'},
  {'code': '+1767', 'flag': '🇩🇲', 'name': 'Dominica'},
  {'code': '+593', 'flag': '🇪🇨', 'name': 'Ecuador'},
  {'code': '+20', 'flag': '🇪🇬', 'name': 'Egipto'},
  {'code': '+503', 'flag': '🇸🇻', 'name': 'El Salvador'},
  {'code': '+971', 'flag': '🇦🇪', 'name': 'Emiratos Árabes Unidos'},
  {'code': '+291', 'flag': '🇪🇷', 'name': 'Eritrea'},
  {'code': '+421', 'flag': '🇸🇰', 'name': 'Eslovaquia'},
  {'code': '+386', 'flag': '🇸🇮', 'name': 'Eslovenia'},
  {'code': '+34', 'flag': '🇪🇸', 'name': 'España'},
  {'code': '+1', 'flag': '🇺🇸', 'name': 'Estados Unidos'},
  {'code': '+372', 'flag': '🇪🇪', 'name': 'Estonia'},
  {'code': '+251', 'flag': '🇪🇹', 'name': 'Etiopía'},
  {'code': '+679', 'flag': '🇫🇯', 'name': 'Fiyi'},
  {'code': '+63', 'flag': '🇵🇭', 'name': 'Filipinas'},
  {'code': '+358', 'flag': '🇫🇮', 'name': 'Finlandia'},
  {'code': '+33', 'flag': '🇫🇷', 'name': 'Francia'},
  {'code': '+241', 'flag': '🇬🇦', 'name': 'Gabón'},
  {'code': '+220', 'flag': '🇬🇲', 'name': 'Gambia'},
  {'code': '+995', 'flag': '🇬🇪', 'name': 'Georgia'},
  {'code': '+233', 'flag': '🇬🇭', 'name': 'Ghana'},
  {'code': '+30', 'flag': '🇬🇷', 'name': 'Grecia'},
  {'code': '+1473', 'flag': '🇬🇩', 'name': 'Granada'},
  {'code': '+502', 'flag': '🇬🇹', 'name': 'Guatemala'},
  {'code': '+224', 'flag': '🇬🇳', 'name': 'Guinea'},
  {'code': '+240', 'flag': '🇬🇶', 'name': 'Guinea Ecuatorial'},
  {'code': '+245', 'flag': '🇬🇼', 'name': 'Guinea-Bisáu'},
  {'code': '+592', 'flag': '🇬🇾', 'name': 'Guyana'},
  {'code': '+509', 'flag': '🇭🇹', 'name': 'Haití'},
  {'code': '+504', 'flag': '🇭🇳', 'name': 'Honduras'},
  {'code': '+36', 'flag': '🇭🇺', 'name': 'Hungría'},
  {'code': '+91', 'flag': '🇮🇳', 'name': 'India'},
  {'code': '+62', 'flag': '🇮🇩', 'name': 'Indonesia'},
  {'code': '+964', 'flag': '🇮🇶', 'name': 'Irak'},
  {'code': '+98', 'flag': '🇮🇷', 'name': 'Irán'},
  {'code': '+353', 'flag': '🇮🇪', 'name': 'Irlanda'},
  {'code': '+354', 'flag': '🇮🇸', 'name': 'Islandia'},
  {'code': '+972', 'flag': '🇮🇱', 'name': 'Israel'},
  {'code': '+39', 'flag': '🇮🇹', 'name': 'Italia'},
  {'code': '+1876', 'flag': '🇯🇲', 'name': 'Jamaica'},
  {'code': '+81', 'flag': '🇯🇵', 'name': 'Japón'},
  {'code': '+962', 'flag': '🇯🇴', 'name': 'Jordania'},
  {'code': '+7', 'flag': '🇰🇿', 'name': 'Kazajistán'},
  {'code': '+254', 'flag': '🇰🇪', 'name': 'Kenia'},
  {'code': '+996', 'flag': '🇰🇬', 'name': 'Kirguistán'},
  {'code': '+686', 'flag': '🇰🇮', 'name': 'Kiribati'},
  {'code': '+965', 'flag': '🇰🇼', 'name': 'Kuwait'},
  {'code': '+856', 'flag': '🇱🇦', 'name': 'Laos'},
  {'code': '+266', 'flag': '🇱🇸', 'name': 'Lesoto'},
  {'code': '+371', 'flag': '🇱🇻', 'name': 'Letonia'},
  {'code': '+961', 'flag': '🇱🇧', 'name': 'Líbano'},
  {'code': '+231', 'flag': '🇱🇷', 'name': 'Liberia'},
  {'code': '+218', 'flag': '🇱🇾', 'name': 'Libia'},
  {'code': '+423', 'flag': '🇱🇮', 'name': 'Liechtenstein'},
  {'code': '+370', 'flag': '🇱🇹', 'name': 'Lituania'},
  {'code': '+352', 'flag': '🇱🇺', 'name': 'Luxemburgo'},
  {'code': '+261', 'flag': '🇲🇬', 'name': 'Madagascar'},
  {'code': '+60', 'flag': '🇲🇾', 'name': 'Malasia'},
  {'code': '+265', 'flag': '🇲🇼', 'name': 'Malaui'},
  {'code': '+960', 'flag': '🇲🇻', 'name': 'Maldivas'},
  {'code': '+223', 'flag': '🇲🇱', 'name': 'Malí'},
  {'code': '+356', 'flag': '🇲🇹', 'name': 'Malta'},
  {'code': '+212', 'flag': '🇲🇦', 'name': 'Marruecos'},
  {'code': '+230', 'flag': '🇲🇺', 'name': 'Mauricio'},
  {'code': '+222', 'flag': '🇲🇷', 'name': 'Mauritania'},
  {'code': '+52', 'flag': '🇲🇽', 'name': 'México'},
  {'code': '+691', 'flag': '🇫🇲', 'name': 'Micronesia'},
  {'code': '+373', 'flag': '🇲🇩', 'name': 'Moldavia'},
  {'code': '+377', 'flag': '🇲🇨', 'name': 'Mónaco'},
  {'code': '+976', 'flag': '🇲🇳', 'name': 'Mongolia'},
  {'code': '+382', 'flag': '🇲🇪', 'name': 'Montenegro'},
  {'code': '+258', 'flag': '🇲🇿', 'name': 'Mozambique'},
  {'code': '+95', 'flag': '🇲🇲', 'name': 'Myanmar'},
  {'code': '+264', 'flag': '🇳🇦', 'name': 'Namibia'},
  {'code': '+674', 'flag': '🇳🇷', 'name': 'Nauru'},
  {'code': '+977', 'flag': '🇳🇵', 'name': 'Nepal'},
  {'code': '+505', 'flag': '🇳🇮', 'name': 'Nicaragua'},
  {'code': '+227', 'flag': '🇳🇪', 'name': 'Níger'},
  {'code': '+234', 'flag': '🇳🇬', 'name': 'Nigeria'},
  {'code': '+47', 'flag': '🇳🇴', 'name': 'Noruega'},
  {'code': '+64', 'flag': '🇳🇿', 'name': 'Nueva Zelanda'},
  {'code': '+968', 'flag': '🇴🇲', 'name': 'Omán'},
  {'code': '+31', 'flag': '🇳🇱', 'name': 'Países Bajos'},
  {'code': '+92', 'flag': '🇵🇰', 'name': 'Pakistán'},
  {'code': '+680', 'flag': '🇵🇼', 'name': 'Palaos'},
  {'code': '+507', 'flag': '🇵🇦', 'name': 'Panamá'},
  {'code': '+675', 'flag': '🇵🇬', 'name': 'Papúa Nueva Guinea'},
  {'code': '+595', 'flag': '🇵🇾', 'name': 'Paraguay'},
  {'code': '+51', 'flag': '🇵🇪', 'name': 'Perú'},
  {'code': '+48', 'flag': '🇵🇱', 'name': 'Polonia'},
  {'code': '+351', 'flag': '🇵🇹', 'name': 'Portugal'},
  {'code': '+974', 'flag': '🇶🇦', 'name': 'Catar'},
  {'code': '+44', 'flag': '🇬🇧', 'name': 'Reino Unido'},
  {'code': '+236', 'flag': '🇨🇫', 'name': 'República Centroafricana'},
  {'code': '+420', 'flag': '🇨🇿', 'name': 'República Checa'},
  {'code': '+1809', 'flag': '🇩🇴', 'name': 'República Dominicana'},
  {'code': '+250', 'flag': '🇷🇼', 'name': 'Ruanda'},
  {'code': '+40', 'flag': '🇷🇴', 'name': 'Rumania'},
  {'code': '+7', 'flag': '🇷🇺', 'name': 'Rusia'},
  {'code': '+685', 'flag': '🇼🇸', 'name': 'Samoa'},
  {'code': '+378', 'flag': '🇸🇲', 'name': 'San Marino'},
  {'code': '+1869', 'flag': '🇰🇳', 'name': 'San Cristóbal y Nieves'},
  {'code': '+1784', 'flag': '🇻🇨', 'name': 'San Vicente y las Granadinas'},
  {'code': '+1758', 'flag': '🇱🇨', 'name': 'Santa Lucía'},
  {'code': '+239', 'flag': '🇸🇹', 'name': 'Santo Tomé y Príncipe'},
  {'code': '+221', 'flag': '🇸🇳', 'name': 'Senegal'},
  {'code': '+381', 'flag': '🇷🇸', 'name': 'Serbia'},
  {'code': '+248', 'flag': '🇸🇨', 'name': 'Seychelles'},
  {'code': '+232', 'flag': '🇸🇱', 'name': 'Sierra Leona'},
  {'code': '+65', 'flag': '🇸🇬', 'name': 'Singapur'},
  {'code': '+963', 'flag': '🇸🇾', 'name': 'Siria'},
  {'code': '+252', 'flag': '🇸🇴', 'name': 'Somalia'},
  {'code': '+94', 'flag': '🇱🇰', 'name': 'Sri Lanka'},
  {'code': '+268', 'flag': '🇸🇿', 'name': 'Suazilandia'},
  {'code': '+27', 'flag': '🇿🇦', 'name': 'Sudáfrica'},
  {'code': '+249', 'flag': '🇸🇩', 'name': 'Sudán'},
  {'code': '+211', 'flag': '🇸🇸', 'name': 'Sudán del Sur'},
  {'code': '+46', 'flag': '🇸🇪', 'name': 'Suecia'},
  {'code': '+41', 'flag': '🇨🇭', 'name': 'Suiza'},
  {'code': '+597', 'flag': '🇸🇷', 'name': 'Surinam'},
  {'code': '+66', 'flag': '🇹🇭', 'name': 'Tailandia'},
  {'code': '+255', 'flag': '🇹🇿', 'name': 'Tanzania'},
  {'code': '+992', 'flag': '🇹🇯', 'name': 'Tayikistán'},
  {'code': '+670', 'flag': '🇹🇱', 'name': 'Timor Oriental'},
  {'code': '+228', 'flag': '🇹🇬', 'name': 'Togo'},
  {'code': '+676', 'flag': '🇹🇴', 'name': 'Tonga'},
  {'code': '+1868', 'flag': '🇹🇹', 'name': 'Trinidad y Tobago'},
  {'code': '+216', 'flag': '🇹🇳', 'name': 'Túnez'},
  {'code': '+993', 'flag': '🇹🇲', 'name': 'Turkmenistán'},
  {'code': '+90', 'flag': '🇹🇷', 'name': 'Turquía'},
  {'code': '+688', 'flag': '🇹🇻', 'name': 'Tuvalu'},
  {'code': '+380', 'flag': '🇺🇦', 'name': 'Ucrania'},
  {'code': '+256', 'flag': '🇺🇬', 'name': 'Uganda'},
  {'code': '+598', 'flag': '🇺🇾', 'name': 'Uruguay'},
  {'code': '+998', 'flag': '🇺🇿', 'name': 'Uzbekistán'},
  {'code': '+678', 'flag': '🇻🇺', 'name': 'Vanuatu'},
  {'code': '+58', 'flag': '🇻🇪', 'name': 'Venezuela'},
  {'code': '+84', 'flag': '🇻🇳', 'name': 'Vietnam'},
  {'code': '+967', 'flag': '🇾🇪', 'name': 'Yemen'},
  {'code': '+260', 'flag': '🇿🇲', 'name': 'Zambia'},
  {'code': '+263', 'flag': '🇿🇼', 'name': 'Zimbabue'},
];

String countryFlagLabel(String flag) {
  final runes = flag.runes.toList(growable: false);
  if (runes.length == 2 && runes.every((r) => r >= 0x1F1E6 && r <= 0x1F1FF)) {
    return String.fromCharCodes(runes.map((r) => 0x41 + r - 0x1F1E6));
  }
  return flag;
}
